# TT-Metal device profiler test.

load("//bazel:pytest.bzl", "pytest_suite")

pytest_suite(
    name = "profiler_tests",
    srcs = glob(["test_*.py"]),
    deps = [
        "//ttnn/ttnn:ttnn_py",
        "@pip//loguru",
        "@pip//pandas",
    ],
    tags = ["tt_metal", "profiler", "requires_wormhole_b0"],
)
